### ISSUE TITLE
Add SASS to project

### ISSUE THREAD

**Issue by tinuola** [chingu-voyage7/Geckos-Team-10#28]

**Comment by rmcguire6** [comment]
Hello Tinuola,       It's Regina your collaborator from Chingu Voyage 
7. I've been involved with a lot of other projects and have let this 
one slip but my team in Chingu Voyage 9 is going to be submitting our 
team project in about 2 weeks and that reminded me that we never 
submitted this one. We can submit it when the Voyage 9 projects are 
submitted--the deadline is July 14.
       I haven't worked on it recently but I would like to clean it up 
and submit it. If you have any interest in doing anything else with it 
please let me know.
       I do want to thank you for your gracious help and incredible 
design work. I learned a great deal from you that I continue to use 
every time I use JS or git.
       I hope your life is a beautiful balance of enjoyable work and 
play.
Regina
